splash = false

preload = /home/isalgado/Pictures/Wallpapers/wall.jpg

wallpaper {
    monitor = eDP-1
    path = /home/isalgado/Pictures/Wallpapers/wall.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/isalgado/Pictures/Wallpapers/wall.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/isalgado/Pictures/Wallpapers/wall.jpg
    fit_mode = cover
}
